export default {
    web3: 'Web3',
    'web3-utils': 'Web3Utils',
    'web3-eth': 'Web3Eth',
    'web3-eth-accounts': 'Web3EthAccounts',
    'web3-eth-contract': 'Web3EthContract',
    'web3-eth-personal': 'Web3EthPersonal',
    'web3-eth-iban': 'Web3EthIban',
    'web3-eth-abi': 'Web3EthAbi',
    'web3-net': 'Web3Net',
    'web3-shh': 'Web3Shh',
    'web3-bzz': 'Web3Bzz',
    'web3-providers-ipc': 'Web3IpcProvider',
    'web3-providers-http': 'Web3HttpProvider',
    'web3-providers-ws': 'Web3WsProvider',
    'web3-core': 'web3Core',
    'web3-core-helpers': 'web3CoreHelpers',
    'web3-core-subscriptions': 'Web3Subscriptions',
    'web3-core-requestmanager': 'Web3RequestManager',
    'web3-core-promievent': 'Web3PromiEvent',
    'web3-core-method': 'Web3Method'
};
