name: Docs CloudFlare Deploy
on:
    push:
      branches:
        - "4.x"
      tags-ignore:
        - v4*

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            deployments: write
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  cache: yarn
                  node-version: '18'
            - run: yarn install --frozen-lockfile
            - run: yarn run build:docs
            - name: Publish to Cloudflare Pages
              uses: cloudflare/pages-action@v1
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: 2238a825c5aca59233eab1f221f7aefb
                  projectName: web3-js-docs
                  directory: ./docs/build
                  gitHubToken: ${{ secrets.GITHUB_TOKEN }}
